Repository Tamanegi-seoul/Co-meet, pull requests merged in 2022-11, with the labels that each got.

#5 Style : 내 정보수정 페이지 퍼블리싱
  src/components/InformationEdit/UserImg.js
  src/components/InformationEdit/UserStack.js
  src/pages/InformationEdit.js
  src/pages/MainPage.js
Labels: Feature, Html&Css

#7 style : PostComent,PostView,Post.css UI
  src/App.js
  src/components/ReadPage/Post.css
  src/components/ReadPage/PostComent.js
  src/components/ReadPage/PostView.js
  src/index.css
Labels: Html&Css

#8 feat : MainCarousel 클릭 시 페이지 랜더링 및 Header, MainCarousel Css 수정
  public/img/slideimage.jpeg
  src/App.js
  src/components/Header.js
  src/components/MainCarousel.js
  src/pages/MainPage.js
Labels: Feature, Html&Css

#10 feat: 메인페이지 게시글 필터링 적용, 카테고리 버그 수정
  src/components/PostList.js
  src/components/PostPreview.js
  src/components/StackButton/StackButton.js
  src/dummyPost/dummyPost.json
Labels: BugFix, Feature

#11 Style : postPreview css 수정
  src/components/PostPreview.js
Labels: Html&Css

#12 Style/jiyeon2
  src/components/ReadPage/Post.css
  src/components/ReadPage/PostComent.js
  src/components/ReadPage/PostData.json
  src/components/ReadPage/PostView.js
  src/pages/ReadPage.js
Labels: Feature, Html&Css

#13 feat: 댓글 삭제 기능 구현
  src/components/ReadPage/PostComent.js
  src/components/ReadPage/PostData.json
  src/components/ReadPage/PostView.js
Labels: Feature, Html&Css

#14 feat : Stack List Event 구현
  public/img/NodeJs.png
  src/components/StackButton/StackButton.js
  src/components/TeachStack.js
  src/tech_stacks.json
Labels: Feature, Html&Css
