Repository Tamanegi-seoul/Co-meet, pull requests merged in 2022-12, with the labels that each got.

#20 Style : Img 추가 및 마무리 스타일링 작업
  public/img/C++.png
  public/img/C.png
  public/img/Express.png
  public/img/Figma.png
  public/img/Firebase.png
  public/img/Git.png
  public/img/Go.png
  public/img/GraphQL.png
  public/img/Kotlin.png
  public/img/Kubernetes.png
  public/img/NestJS.png
  public/img/NextJS.png
  public/img/NodeJs.png
  public/img/Php.png
  public/img/R.png
  public/img/ReactNative.png
  public/img/Swift.png
  public/img/TypeScript.png
  public/img/Unity.png
  public/img/Zeplin.png
  public/img/mySql.png
  src/components/PostPreview.js
  src/components/StackButton/StackButton.js
Labels: Html&Css

#21 style: mainCarousel 1차퍼블리싱
  public/img/collabo.png
  public/img/collabora.png
  public/img/comeet_main.png
  public/img/slide_img2.png
  src/components/MainCarousel.js
  src/index.css
Labels: Html&Css

#22 feat : multi-select 기능 추가
  src/pages/WritePage.js
Labels: Feature

#24 feat: post scroll시 loading 구현
  package-lock.json
  package.json
  public/img/load.gif
  src/App.js
  src/components/PostList.js
  src/pages/Loading.js
Labels: Feature, Html&Css

#29 Feat : Coment axios 연동 진행
  src/components/ReadPage/PostComent.js
Labels: API

#30 feat: 로그인 구현 테스트
  src/pages/Login.js
  src/pages/SignUp.js
  src/store/user/user.js
  src/store/user/userApi.js
  src/utils/setAuthToken.js
  src/utils/setCookie.js
Labels: Feature, API

#31 feat: jwt_decode추가
  package-lock.json
  package.json
  src/app/store.js
  src/components/Alert/Alert.js
  src/components/MainCarousel.js
  src/components/Modal/ModalUserInfo.js
  src/pages/Login.js
  src/pages/SignUp.js
  src/store/user/user.js
  src/store/user/userApi.js
  src/utils/setCookie.js
Labels: BugFix, Feature, API

#32 feat : Coment 덧글 조회 axios 연동 완료
  src/components/ReadPage/PostComent.js
Labels: Feature, API

#33 Style/jiyeon2
  src/components/ReadPage/PostView.js
  src/pages/WritePage.js
Labels: Feature, API

#36 feat: 개인정보수정 완성
  src/components/Header.js
  src/components/InformationEdit/UserImg.js
  src/components/InformationEdit/UserImgs.js
  src/store/post/post.js
  src/store/user/user.js
  src/store/user/userApi.js
  src/utils/postListRefresh.js
Labels: Feature, API

#42 feat : comment 백 데이터 렌더링 완료
  src/components/ReadPage/PostComent.js
  src/components/ReadPage/PostView.js
Labels: Feature, Html&Css

#46 feat : id값에 맞는 post 조회 성공
  src/components/ReadPage/PostComent.js
  src/components/ReadPage/PostView.js
Labels: Feature

#49 feat : 데이터 뿌리기 완료
  src/components/ReadPage/PostView.js
Labels: Feature

#51 feat : comment post 구현
  package-lock.json
  public/img/Aws.png
  src/components/ReadPage/PostComent.js
Labels: Feature

#52 feat : axios-post요청(post_id 받아오기 완료)
  src/components/ReadPage/PostComent.js
Labels: Feature

#54 Feat : Comment 추가 시 페이지 렌더링 완료
  src/components/ReadPage/PostComent.js
Labels: Feature
