Repository Tamanegi-seoul/Co-meet, pull requests merged in 2023-01, with the labels that each got.

#58 feat : 댓글 등록시 페이지 재렌더링
  src/components/ReadPage/PostComment.js
Labels: Feature

#59 feat : Redirect-Post
  src/components/ReadPage/PostComment.js
  src/components/ReadPage/PostView.js
  src/pages/WritePage.js
Labels: Feature

#64 Feat : 댓글 작성시 이미지 같이 불러오기 진행중
  src/components/InformationEdit/UserImg.js
  src/components/ReadPage/PostComment.js
  src/components/ReadPage/PostView.js
Labels: Feature

#72 Feat : ScrollTop 및 PostPreview-퍼블리싱
  src/App.js
  src/components/PostPreview.js
  src/components/ReadPage/PostComment.js
  src/components/ReadPage/PostView.js
  src/scrollTop.js
Labels: Feature, Html&Css

#86 feat : post Edit 진행 및 취소 버튼시 뒤로가기 활성화
  src/components/ReadPage/PostComment.js
  src/components/ReadPage/PostEdit.js
  src/pages/WritePage.js
Labels: Feature

#90 feat : Api patch - Edit 기능 구현 및 댓글 입력시 keydown 오류 해결
  src/components/PostPreview.js
  src/components/ReadPage/PostComment.js
  src/components/ReadPage/PostEdit.js
  src/components/ReadPage/PostView.js
  src/pages/MyPostList.js
  src/pages/WritePage.js
  src/store/user/userApi.js
Labels: Feature

#93 Feat : Axios Delete Api 기능 구현
  src/components/Modal/ModalDelete.js
  src/components/Modal/ModalRevise.js
  src/components/PostPreview.js
  src/components/ReadPage/PostEdit.js
  src/components/ReadPage/PostView.js
  src/pages/WritePage.js
Labels: Feature

#99 feat : Main 화면 - userImg 띄우기 완료
  src/components/Header.js
  src/components/InformationEdit/UserImg.js
  src/components/Modal/ModalUserInfo.js
  src/components/PostPreview.js
  src/pages/MainPage.js
  src/pages/WritePage.js
  src/store/user/user.js
Labels: Feature, Html&Css

#100 fix : wirtePage 코드 수정 및 header user img 퍼블리싱
  src/components/Modal/ModalUserInfo.js
  src/pages/WritePage.js
Labels: BugFix, Html&Css

#101 feat : 기본 이미지 설정
  src/components/Modal/ModalUserInfo.js
Labels: Feature

#103 fix : comment value값 수정
  src/components/PostList.js
  src/components/PostPreview.js
  src/components/ReadPage/CommentEdit.js
  src/components/ReadPage/CommentList.js
  src/components/ReadPage/PostView.js
Labels: Feature, Html&Css
